"""Generate editable introduction diagrams from the thesis entropy definitions.

All numerical cases are mathematical illustrations. No experiment is changed.
The script writes only into the presentation directory.
"""
from pathlib import Path
import argparse
import hashlib
import json
import math

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--thesis', type=Path, default=root.parent / 'MSc_thesis')
args = parser.parse_args()
figures = root / 'figures'

# Equal probabilities over three possible vectors, or over three weight settings.
# The general hierarchy in eq:general-hierarchy leaves p(pi|x,w) unspecified.
# These discrete examples illustrate that hierarchy, not a fitted Dirichlet model.
low_vectors = [0.45, 0.50, 0.55]
high_vectors = [0.05, 0.50, 0.95]
label_vectors = [0.99, 0.50]

def entropy(p):
    return -p * math.log(p) - (1-p) * math.log(1-p)

def gap(values):
    mean = sum(values)/len(values)
    return entropy(mean) - sum(map(entropy, values))/len(values)

assert abs(sum(low_vectors)/3 - sum(high_vectors)/3) < 1e-12
assert 0 < gap(low_vectors) < gap(high_vectors)
assert entropy(label_vectors[0]) < entropy(label_vectors[1])

def text(x, y, content, size=r'\normalsize', align='l'):
    return rf'\put({x},{y}){{\makebox(0,4)[{align}]{{{size} {content}}}}}'

def bar(x, y, p, width=57, height=5):
    return (rf'\put({x},{y}){{\hbox{{\color{{lmugreen}}\rule{{{width*p:.6f}mm}}{{{height}mm}}'
            rf'\color{{introblue}}\rule{{{width*(1-p):.6f}mm}}{{{height}mm}}}}}}')

def arrow(x, y, length, direction=(1, 0)):
    return rf'\put({x},{y}){{\vector({direction[0]},{direction[1]}){{{length}}}}}'

def diagram(name, height, lines, source):
    header = ['% Generated by scripts/build_intro_explanations.py.',
              '% Mathematical illustration. ' + source,
              r'\setlength{\unitlength}{1mm}',
              rf'\begin{{picture}}(140,{height})']
    (figures/name).write_text('\n'.join(header + lines + [r'\end{picture}']) + '\n')

lines = []
for x, p, label in [(4, .99, 'Lower predictive uncertainty'), (79, .5, 'Higher predictive uncertainty')]:
    lines += [text(x+28.5, 29, rf'\textbf{{{label}}}', align='c'), bar(x, 17, p),
              text(x, 7, rf'Class A\quad {100*p:.0f}\%'),
              text(x+57, 7, rf'Class B\quad {100*(1-p):.0f}\%', align='r')]
diagram('intro_predictive_example.tex', 36, lines, 'Background 2.6, eq:shannon-entropy.')

lines = []
for x, p, label in [(4, .99, 'Lower label entropy'), (79, .5, 'Higher label entropy')]:
    lines += [text(x+28.5, 35, rf'\textbf{{{label}}}', align='c'), bar(x, 25, p),
              text(x, 18, rf'Class A\quad {100*p:.0f}\%'),
              text(x+57, 18, rf'Class B\quad {100*(1-p):.0f}\%', align='r'),
              arrow(x+28.5, 15, 5, (0,-1)),
              text(x+28.5, 1, r'\textcolor{lmugreen}{Class A}\quad or\quad\textcolor{introblue}{Class B}', align='c')]
diagram('intro_aleatoric_example.tex', 42, lines, 'Background 2.6, eq:expected-conditional-entropy, and eq:categorical-likelihood.')

lines = []
for x, values, label in [(0, low_vectors, 'Lower distributional term'), (75, high_vectors, 'Higher distributional term')]:
    lines += [text(x+32.5, 30, rf'\textbf{{{label}}}', align='c'),
              text(x+9, 14, r'\shortstack{Fixed\\weights}', align='c'), arrow(x+22, 17, 5)]
    for y, p in zip([22, 15, 8], values):
        lines += [bar(x+29, y, p, width=35, height=3.5)]
    lines += [text(x+32.5, 0, r'Average probabilities\quad 50\% / 50\%', size=r'\small', align='c')]
diagram('intro_distributional_example.tex', 36, lines, 'Background 2.7, eq:fixed-weight-decomposition. Three equally likely vectors in each example.')

lines = []
for x, values, label in [(0, low_vectors, 'Lower epistemic term'), (75, high_vectors, 'Higher epistemic term')]:
    lines += [text(x+32.5, 30, rf'\textbf{{{label}}}', align='c')]
    for j, (y, p) in enumerate(zip([22,15,8], values), start=1):
        lines += [text(x, y, f'Weights {j}', size=r'\small'), arrow(x+22, y+2, 5),
                  bar(x+29, y, p, width=35, height=3.5)]
    lines += [text(x+32.5, 0, r'Average probabilities\quad 50\% / 50\%', size=r'\small', align='c')]
diagram('intro_epistemic_example.tex', 36, lines, 'Background 2.7, eq:weight-level-decomposition. Three equally likely weight settings in each example.')

lines = []
for offset, name, left, middle, left_term, middle_term in [
    (28, r'\textbf{Categorical Bayesian neural network (Cat-BNN)}',
     r'\shortstack{Plausible network\\weights}', r'\shortstack{One class-probability vector\\at each weight configuration}',
     'Epistemic uncertainty', r'\textbf{Distributional term zero}'),
    (0, r'\textbf{Evidential deep learning (EDL)}',
     'One weight estimate', r'\shortstack{Distribution over\\class-probability vectors}',
     r'\textbf{Epistemic term zero}', 'Distributional uncertainty')]:
    lines += [text(0, offset+20, name),
              text(22, offset+10, left, size=r'\small', align='c'), arrow(44, offset+12, 6),
              text(79, offset+10, middle, size=r'\small', align='c'), arrow(109, offset+12, 6),
              text(128, offset+10, 'Class label', size=r'\small', align='c'),
              text(22, offset+1, left_term, size=r'\small', align='c'),
              text(79, offset+1, middle_term, size=r'\small', align='c'),
              text(128, offset+1, 'Aleatoric uncertainty', size=r'\small', align='c')]
diagram('intro_model_gap.tex', 53, lines, 'Discussion 6.1, eq:degenerate-distributional-term and eq:point-estimate-epistemic-term.')

source_paths = [args.thesis/'chapters/background.tex', args.thesis/'chapters/introduction.tex', args.thesis/'chapters/discussion.tex']
record = {
    'generator': 'scripts/build_intro_explanations.py',
    'kind': 'Mathematical illustrations. No experimental results.',
    'sources': {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in source_paths},
    'label_class_A_probabilities': label_vectors,
    'label_entropies_nats': [entropy(p) for p in label_vectors],
    'low_variation_class_A_probabilities': low_vectors,
    'high_variation_class_A_probabilities': high_vectors,
    'probability_of_each_vector_or_weight_setting': 1/3,
    'low_information_nats': gap(low_vectors),
    'high_information_nats': gap(high_vectors),
    'visible_percentages': 'Exact mathematical example parameters. No rounded experimental results.',
    'theory_labels': ['eq:shannon-entropy','eq:expected-conditional-entropy','eq:fixed-weight-decomposition','eq:weight-level-decomposition','eq:three-way-decomposition']
}
(figures/'intro_explanations_sources.json').write_text(json.dumps(record, indent=2)+'\n')
print('Built five editable diagrams and checked the entropy comparisons.')
