"""Build the observed multiclass disagreement example from local CIFAR-10H data."""
from pathlib import Path
import hashlib
import json
import pickle
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT.parent / "BNN-EDL" / "data"
COUNTS = DATA / "cifar10h" / "cifar10h-counts.npy"
IMAGES = DATA / "cifar-10-batches-py" / "test_batch"
counts = np.load(COUNTS)
proportions = counts / counts.sum(axis=1, keepdims=True)
entropies = -(proportions * np.log(np.clip(proportions, 1e-15, None))).sum(axis=1)
index = int(np.argmax(entropies))
assert index == 6750
with IMAGES.open("rb") as f:
    batch = pickle.load(f, encoding="bytes")
images = batch[b"data"].reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1)
labels = ["Airplane", "Car", "Bird", "Cat", "Deer", "Dog", "Frog", "Horse", "Ship", "Truck"]
n = counts[index].astype(int)
assert n.sum() == 52 and (n > 0).sum() == 9
Image.fromarray(images[index]).save(ROOT / "figures/cifar10h_multiclass_input.png")
plt.rcParams.update({"font.family": "sans-serif", "font.size": 11, "pdf.fonttype": 42})
fig, ax = plt.subplots(figsize=(6.5, 2.85))
fig.subplots_adjust(left=.085, right=.99, bottom=.25, top=.92)
x = np.arange(10)
ax.bar(x, n, width=.68, color="#00883A", zorder=3)
ax.set_xticks(x, labels, rotation=30, ha="right", rotation_mode="anchor")
ax.set_ylabel("Number of labels")
ax.set_ylim(0, 15)
ax.set_yticks([0, 5, 10, 15])
ax.set_xlim(-.65, 9.65)
ax.grid(axis="y", color="#e6e6e6", zorder=0)
ax.spines[["top", "right"]].set_visible(False)
ax.tick_params(axis="x", length=0)
for j, value in enumerate(n):
    ax.text(j, value + .35, str(value), ha="center", va="bottom", fontsize=11)
for suffix in ["pdf", "png"]:
    fig.savefig(ROOT / f"figures/cifar10h_multiclass_counts.{suffix}", dpi=180)
plt.close(fig)
(ROOT / "tables/repeated_label_example.tex").write_text(
    "% Generated by scripts/build_repeated_label_example.py.\n"
    f"\\def\\repeatedexampleindex{{{index}}}\n"
    f"\\def\\repeatedexampletotal{{{n.sum()}}}\n"
)
metadata = {
    "generator": "scripts/build_repeated_label_example.py",
    "selection": "Maximum entropy of observed human label proportions across all 10000 images. Illustrative selection, not a representative sample.",
    "image_index": index,
    "original_cifar10_label": labels[batch[b"labels"][index]],
    "classes": labels,
    "counts": n.tolist(),
    "label_total": int(n.sum()),
    "observed_label_entropy": float(entropies[index]),
    "sources": {str(p): hashlib.sha256(p.read_bytes()).hexdigest() for p in [COUNTS, IMAGES]},
}
(ROOT / "figures/repeated_label_example.sources.json").write_text(json.dumps(metadata, indent=2) + "\n")
print(f"Image {index}, counts {n.tolist()}, total {n.sum()}.")
