"""Export one original CIFAR-10 image and its saved model predictions.

Use the final BMA and stored uncertainty terms from one DM-eBNN run.
Only presentation files are written. No experiments or source images change.
"""
from pathlib import Path
import argparse
import hashlib
import json
import pickle
import numpy as np
from PIL import Image

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--experiments', type=Path, default=root.parent / 'BNN-EDL')
args = parser.parse_args()
figures = root / 'figures'
run = 'e2_c10h_ebnn_dm_mode50_warm_s0'
array_path = args.experiments / 'outputs' / run / 'arrays/cifar10h_test.npz'
counts_path = args.experiments / 'data/cifar10h/cifar10h-counts.npy'
image_path = args.experiments / 'data/cifar-10-batches-py/test_batch'
a = np.load(array_path, allow_pickle=False)
row = 258
image_index = 2078
counts = np.load(counts_path, allow_pickle=False)
# Saved indices are local to the held-out split. Match the full count vector
# uniquely to verify the original CIFAR-10 image, rather than reusing that index.
matches = np.flatnonzero(np.all(counts == a['true_counts'][row], axis=1))
assert matches.tolist() == [image_index], matches
with image_path.open('rb') as handle:
    batch = pickle.load(handle, encoding='bytes')
images = batch[b'data'].reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1)
image_file = figures / 'cifar_ambiguous_input.png'
Image.fromarray(images[image_index]).save(image_file)
assert np.array_equal(np.asarray(Image.open(image_file)), images[image_index])

classes = ['airplane', 'automobile', 'bird', 'cat', 'deer',
           'dog', 'frog', 'horse', 'ship', 'truck']
raw_p = a['snapshot_means'][:, row, :].astype(np.float64).mean(axis=0)
# The analysis normalises probabilities stored in float16 before entropy checks.
p = raw_p / raw_p.sum()
assert int(np.argmax(p)) == int(a['pred_class'][row])
terms = {name: float(a[name][row]) for name in
         ['aleatoric', 'distributional', 'epistemic']}
assert all(value >= 0 for value in terms.values())
total = sum(terms.values())
entropy = float(-(p * np.log(np.clip(p, 1e-12, None))).sum())
assert abs(total - entropy) < 5e-5  # Float16 saved means versus float32 terms.
shares = {name: 100 * value / total for name, value in terms.items()}

def text(x, y, label, align='c', size=r'\small'):
    return rf'\put({x},{y}){{\makebox(0,3)[{align}]{{{size} {label}}}}}'

lines = [r'% Generated by scripts/build_cifar_ambiguous_example.py.',
         r'% Final BMA over all 40 saved weight samples. Source details in cifar_ambiguous_sources.json.',
         r'\setlength{\unitlength}{1mm}', r'\begin{picture}(124,45)(0,-7)',
         r'\put(4,6){\includegraphics[width=31mm]{figures/cifar_ambiguous_input.png}}',
         text(19.5, 1, 'CIFAR-10 image'),
         text(46, 25, ''), r'\put(39,21){\vector(1,0){15}}']
for j, (label, prob) in enumerate(zip(classes, p)):
    y = 33 - 3.5 * j
    color = 'lmugreen' if j == np.argmax(p) else 'introblue'
    lines += [text(68, y, label, 'r', r'\fontsize{9}{10}\selectfont'),
              rf'\put(70,{y+.5}){{\textcolor{{{color}}}{{\rule{{{50*prob:.8f}mm}}{{2.1mm}}}}}}']
lines += [r'\put(70,0.5){\line(1,0){50}}']
for tick, label in [(0, '0'), (.5, '0.5'), (1, '1')]:
    x = 70 + 50 * tick
    lines += [rf'\put({x},0.5){{\line(0,-1){{.7}}}}', text(x, -3.8, label)]
lines += [text(95, -7, 'Class probability'), r'\end{picture}']
(figures / 'cifar_ambiguous_prediction.tex').write_text('\n'.join(lines) + '\n')

order = [('aleatoric', 'Data', 'introblue'),
         ('epistemic', 'Model', 'lmugreen'),
         ('distributional', 'Distributional', 'orange!85!black')]
lines = [r'% Generated by scripts/build_cifar_ambiguous_example.py.',
         r'% Stored model terms divided by their sum. These are not known real-world source proportions.',
         r'\setlength{\unitlength}{1mm}', r'\begin{picture}(132,23)(0,-2)',
         text(66, 17, 'Model decomposition for the same image', size=r'\normalsize')]
x = 6.0
for name, label, color in order:
    width = 111 * shares[name] / 100
    lines += [rf'\put({x:.8f},9){{\textcolor{{{color}}}{{\rule{{{width:.8f}mm}}{{4mm}}}}}}']
    x += width
for x, (name, label, color) in zip([6, 47, 84], order):
    lines += [rf'\put({x},2.4){{\textcolor{{{color}}}{{\rule{{2mm}}{{2mm}}}}}}',
              text(x + 3, 2, rf'{label} {shares[name]:.2f}\%', 'l')]
lines += [r'\end{picture}']
(figures / 'cifar_ambiguous_decomposition.tex').write_text('\n'.join(lines) + '\n')

sources = [array_path, counts_path, image_path,
           args.experiments / 'analysis/count_likelihoods.py',
           args.experiments / 'analysis/common/predictive.py',
           args.experiments / 'src/data/loader.py']
record = {
    'generator': 'scripts/build_cifar_ambiguous_example.py',
    'run': run, 'model': 'DM-eBNN', 'split': 'cifar10h_test',
    'evaluation': 'Final BMA over all saved samples',
    'weight_samples': int(a['snapshot_means'].shape[0]),
    'split_row': row, 'split_index': int(a['index'][row]),
    'cifar10_test_image_index': image_index,
    'image_mapping': 'Unique exact match of the saved count vector to the original CIFAR-10H counts',
    'selection': 'Visually ambiguous example among held-out images with high observed label disagreement and maximum predicted probability below 0.7. Not a representative performance estimate.',
    'classes': classes, 'predicted_class': classes[int(np.argmax(p))],
    'original_label': classes[int(batch[b'labels'][image_index])],
    'probabilities_from_float16_means': raw_p.tolist(),
    'probabilities_normalised': p.tolist(),
    'uncertainty_terms_nats': terms, 'predictive_uncertainty_nats': total,
    'entropy_check_nats': entropy, 'uncertainty_shares_percent': shares,
    'observed_counts_for_provenance_only': a['true_counts'][row].tolist(),
    'scope': 'One fitted model, one seed, one image. The decomposition is a model output, not measured real-world sources or a validated decision rule. It depends on the model, prior and inference.',
    'sources': {str(path): hashlib.sha256(path.read_bytes()).hexdigest() for path in sources},
}
(figures / 'cifar_ambiguous_sources.json').write_text(json.dumps(record, indent=2) + '\n')
print(json.dumps({'image_index': image_index, 'shares_percent': shares,
                  'max_entropy_check_error': abs(total - entropy)}))
