"""Export original CIFAR-10 images and saved predictions for the opening slide.

The final BMA uses all saved samples, as in analysis/common/predictive.py.
The selected images illustrate different predictive entropies within one run.
They are not a performance comparison. Only the presentation receives outputs.
"""
from pathlib import Path
import argparse
import hashlib
import json
import pickle
import numpy as np
from PIL import Image

root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser()
parser.add_argument('--experiments',type=Path,default=root.parent/'BNN-EDL')
parser.add_argument('--thesis',type=Path,default=root.parent/'MSc_thesis')
parser.add_argument('--single-example-only',action='store_true',
                    help='Extract one chart from the recorded probabilities without regenerating existing figures.')
args=parser.parse_args()
figures=root/'figures'
if args.single_example_only:
    saved=json.loads((figures/'cifar_opening_sources.json').read_text())
    example=next(r for r in saved['examples'] if r['name']=='higher')
    lines=[r'% Generated by scripts/build_cifar_opening.py --single-example-only.',
           r'% Uses the unchanged saved probabilities in cifar_opening_sources.json.',
           r'\setlength{\unitlength}{1mm}',r'\begin{picture}(94,38)(0,-7)',
           r'\put(0,7){\includegraphics[width=23mm]{figures/cifar_opening_higher.png}}',
           r'\put(11.5,2){\makebox(0,3)[c]{\small CIFAR-10 image}}',
           r'\put(26,18){\vector(1,0){6}}']
    for j,(label,p) in enumerate(zip(saved['classes'],example['probabilities'])):
        y=28.5-3*j
        color='lmugreen' if label==example['predicted_class'] else 'introblue'
        lines += [rf'\put(62,{y}){{\makebox(0,3)[r]{{\fontsize{{9}}{{10}}\selectfont {label}}}}}',
                  rf'\put(63,{y+.5}){{\textcolor{{{color}}}{{\rule{{{28*p:.8f}mm}}{{1.9mm}}}}}}']
    lines += [r'\put(63,0.5){\line(1,0){28}}']
    for tick,label in [(0,'0'),(.5,'0.5'),(1,'1')]:
        pos=63+28*tick
        lines += [rf'\put({pos},0.5){{\line(0,-1){{.7}}}}',
                  rf'\put({pos},-3.8){{\makebox(0,3)[c]{{\fontsize{{9}}{{10}}\selectfont {label}}}}}']
    lines += [r'\put(77,-7){\makebox(0,3)[c]{\small Class probability}}',r'\end{picture}']
    (figures/'cifar_classification_example.tex').write_text('\n'.join(lines)+'\n')
    print('Extracted one existing CIFAR-10 example with all ten saved probabilities.')
    raise SystemExit(0)
run='e1_c10_bnn_T1_warm_s0'
array_path=args.experiments/'outputs'/run/'arrays/cifar10_test.npz'
image_path=args.experiments/'data/cifar-10-batches-py/test_batch'
a=np.load(array_path,allow_pickle=False)
probs=np.asarray(a['snapshot_means'],dtype=np.float64).mean(axis=0)
with image_path.open('rb') as handle:
    batch=pickle.load(handle,encoding='bytes')
images=batch[b'data'].reshape(-1,3,32,32).transpose(0,2,3,1)
classes=['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']
selected=[('lower',9310),('higher',3901)]
records=[]
for name,index in selected:
    row=int(np.flatnonzero(a['index']==index)[0])
    p=probs[row]
    predicted=int(np.argmax(p))
    assert predicted==int(a['pred_class'][row])
    assert int(batch[b'labels'][index])==int(a['true_label'][row])
    assert p.shape==(10,) and np.all(p>=0) and abs(float(p.sum())-1)<.001
    output=figures/f'cifar_opening_{name}.png'
    Image.fromarray(images[index]).save(output)
    assert np.array_equal(np.asarray(Image.open(output)),images[index])
    entropy=float(-(p*np.log(np.clip(p,1e-12,None))).sum())
    records.append({'name':name,'image_index':index,'row':row,'probabilities':p.tolist(),
                    'entropy_nats':entropy,'predicted_class':classes[predicted],
                    'true_class':classes[int(a['true_label'][row])]})
assert records[0]['entropy_nats']<records[1]['entropy_nats']

# Native editable bars. The original 32 x 32 images are embedded without alteration.
def text_at(x,y,label,align='l',size=r'\fontsize{8.2}{9}\selectfont'):
    return rf'\put({x},{y}){{\makebox(0,3)[{align}]{{{size} {label}}}}}'
lines=[r'% Generated by scripts/build_cifar_opening.py from the recorded final BMA.',
       r'\setlength{\unitlength}{1mm}',r'\begin{picture}(140,43)(0,-3)']
for x,record,heading in zip([0,75],records,['Lower predictive uncertainty','Higher predictive uncertainty']):
    lines += [text_at(x+34,36,rf'\textbf{{{heading}}}',align='c',size=r'\normalsize'),
              rf'\put({x},10){{\includegraphics[width=18mm]{{figures/cifar_opening_{record["name"]}.png}}}}',
              rf'\put({x+20},19){{\vector(1,0){{4}}}}']
    for j,(label,p) in enumerate(zip(classes,record['probabilities'])):
        y=31-3*j
        color='lmugreen' if label==record['predicted_class'] else 'introblue'
        lines += [text_at(x+43,y,label,align='r'),
                  rf'\put({x+44},{y+.4}){{\textcolor{{{color}}}{{\rule{{{25*p:.8f}mm}}{{1.9mm}}}}}}']
    lines += [rf'\put({x+44},2){{\line(1,0){{25}}}}']
    for tick,label in [(0,'0'),(.5,'0.5'),(1,'1')]:
        pos=x+44+25*tick
        lines += [rf'\put({pos},2){{\line(0,-1){{.7}}}}',text_at(pos,-2.5,label,align='c')]
lines += [r'\end{picture}']
(figures/'cifar_opening_comparison.tex').write_text('\n'.join(lines)+'\n')
source_paths=[array_path,image_path,args.experiments/'analysis/common/predictive.py',
              args.thesis/'chapters/background.tex',args.thesis/'chapters/experiments.tex']
record={'generator':'scripts/build_cifar_opening.py','run':run,
        'evaluation':'Final BMA over all saved weight samples',
        'weight_samples':int(a['snapshot_means'].shape[0]),'classes':classes,
        'examples':records,
        'entropy_definition':'eq:shannon-entropy. Natural logarithm. Used to verify the contrast, not displayed as a rounded measurement.',
        'sources':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in source_paths}}
(figures/'cifar_opening_sources.json').write_text(json.dumps(record,indent=2)+'\n')
print('Exported original CIFAR-10 images and all ten saved class probabilities.')
