"""Build presentation figures from thesis equations and unchanged analysis outputs.

Run with the BNN-EDL Python environment. This script only writes inside the
presentation folder. All illustrative distributions are marked as illustrations.
"""
from pathlib import Path
import argparse
import hashlib
import json
import pickle
import re

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from scipy.special import digamma
from scipy.stats import beta, betabinom, binom, gamma

parser = argparse.ArgumentParser()
root = Path(__file__).resolve().parents[1]
parser.add_argument('--experiments', type=Path, default=root.parent / 'BNN-EDL')
parser.add_argument('--thesis', type=Path, default=root.parent / 'MSc_thesis')
args = parser.parse_args()
figures, tables = root / 'figures', root / 'tables'
figures.mkdir(exist_ok=True)
tables.mkdir(exist_ok=True)
GREEN, BLUE, ORANGE, GREY = '#00883a', '#326a9f', '#bb741d', '#777777'
plt.rcParams.update({
    'font.family': 'DejaVu Sans', 'font.size': 13, 'axes.labelsize': 13,
    'axes.titlesize': 14, 'axes.spines.top': False, 'axes.spines.right': False,
    'axes.edgecolor': '#aaaaaa', 'xtick.color': '#444444', 'ytick.color': '#444444',
    'legend.frameon': False, 'savefig.facecolor': 'white', 'pdf.fonttype': 42,
})
sources = {}
def record(path):
    sources[str(path)] = hashlib.sha256(path.read_bytes()).hexdigest()
    return path

def save(fig, name):
    fig.savefig(figures / f'{name}.pdf', bbox_inches='tight', pad_inches=0.12)
    fig.savefig(figures / f'{name}.png', dpi=160, bbox_inches='tight', pad_inches=0.12)
    plt.close(fig)

def analysis_table(name):
    path = record(args.experiments / 'results' / f'{name}.tex')
    reference = record(args.thesis / 'tables' / f'{name}.tex')
    assert path.read_bytes() == reference.read_bytes(), f'Analysis output differs from the thesis for {name}'
    return path.read_text()

def cells(line):
    return [part.strip() for part in line.rstrip().removesuffix('\\\\').split('&')]

def stats(cell):
    return [float(s) for s in re.findall(r'\d+(?:\.\d+)?', cell)]

def tabular(name, header, content, columns):
    text = '% Generated by scripts/build_figures.py from unchanged thesis analysis outputs.\n'
    text += '\\begin{tabular}{' + columns + '}\n\\toprule\n'
    text += header + ' \\\\\n\\midrule\n'
    text += '\n'.join(content) + '\n\\bottomrule\n\\end{tabular}\n'
    (tables / name).write_text(text)

# Actual CIFAR-10H image and its observed labels. Index uses CIFAR-10 test order.
counts_path = record(args.experiments / 'data/cifar10h/cifar10h-counts.npy')
image_path = record(args.experiments / 'data/cifar-10-batches-py/test_batch')
counts = np.load(counts_path)
with image_path.open('rb') as handle:
    batch = pickle.load(handle, encoding='bytes')
images = batch[b'data'].reshape(-1, 3, 32, 32).transpose(0, 2, 3, 1)
example = 4195
example_counts = counts[example].astype(int)
Image.fromarray(images[example]).save(figures / 'cifar10h_example.png')
names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
fig, ax = plt.subplots(figsize=(7.6, 3.6))
positions = np.arange(10)
ax.bar(positions, example_counts, color=[GREEN if v else '#dddddd' for v in example_counts], width=.65)
ax.set_xticks(positions, names, rotation=35, ha='right', fontsize=11)
ax.set_ylabel('Number of labels')
ax.set_ylim(0, 34)
for pos, value in zip(positions, example_counts):
    ax.text(pos, value + .7, str(value), ha='center', fontsize=12)
ax.spines['bottom'].set_visible(False)
ax.tick_params(axis='x', length=0)
save(fig, 'observed_counts')
(tables / 'example.tex').write_text(
    f'\\newcommand{{\\exampleindex}}{{{example}}}\n'
    f'\\newcommand{{\\exampletotal}}{{{int(example_counts.sum())}}}\n'
    '\\newcommand{\\examplecounts}{(' + ','.join(map(str, example_counts)) + ')}\n'
)

# Two class illustration. All distributions have mean vector (0.5, 0.5).
# Thesis eq:dirichlet-density and eq:aleatoric-as-function-of-total-concentration.
prob = np.linspace(.001, .999, 500)
fig, axs = plt.subplots(1, 2, figsize=(10.6, 3.25), gridspec_kw={'wspace': .35})
for total, color in [(4, BLUE), (40, GREEN)]:
    axs[0].plot(prob, beta.pdf(prob, total/2, total/2), color=color, lw=2.6,
                label=rf'$\alpha_0={total}$')
axs[0].axvline(.5, color=GREY, ls=':', lw=1.2)
axs[0].set(xlabel=r'Class probability $\pi_1$', ylabel='Density', title='The mean stays fixed')
axs[0].legend(loc='upper left', fontsize=12)
totals = np.geomspace(2.05, 100, 400)
aleatoric = digamma(totals+1)-digamma(totals/2+1)
entropy = np.log(2)
axs[1].plot(totals, aleatoric, color=BLUE, lw=2.6, label='Aleatoric')
axs[1].plot(totals, entropy-aleatoric, color=ORANGE, lw=2.6, label='Distributional')
axs[1].axhline(entropy, color=GREY, ls=':', lw=1.3, label='Their sum')
axs[1].set(xlabel=r'Total concentration parameter $\alpha_0$', ylabel='Uncertainty in nats',
           title='The allocation changes', xscale='log', ylim=(0,.79))
axs[1].legend(loc='center right', fontsize=11)
save(fig, 'mean_and_concentration')

# Cover illustration from the same generic Dirichlet definition, three classes.
# No experimental interpretation is assigned to this illustration.
rng = np.random.default_rng(6)
samples = rng.dirichlet([4, 7, 10], 2200)
xy = samples @ np.array([[0,0],[1,0],[.5,np.sqrt(3)/2]])
fig, ax = plt.subplots(figsize=(4, 3.5))
ax.scatter(xy[:,0], xy[:,1], s=6, alpha=.23, color=GREEN, linewidths=0)
ax.plot([0,1,.5,0],[0,0,np.sqrt(3)/2,0], color='#b0b0b0', lw=1)
ax.text(0,-.05,'Class 1', ha='center', fontsize=12)
ax.text(1,-.05,'Class 2', ha='center', fontsize=12)
ax.text(.5,.9,'Class 3', ha='center', fontsize=12)
ax.set_aspect('equal'); ax.axis('off')
save(fig, 'dirichlet_cover')

# Gamma distributions from eq:gamma-mode and eq:gamma-mean-variance.
fig, ax = plt.subplots(figsize=(7.4, 2.8))
x = np.linspace(.05, 280, 900)
for sd, color in [(20, GREEN), (60, BLUE)]:
    rate = (100+np.sqrt(100**2+4*sd**2))/(2*sd**2)
    shape = 100*rate+1
    ax.plot(x, gamma.pdf(x, shape, scale=1/rate), color=color, lw=2.6,
            label=f'Prior standard deviation {sd}%')
ax.axvline(100, color=GREY, ls=':', lw=1.3)
ax.set(xlabel='Total concentration parameter', ylabel='Prior density', xlim=(0,280))
ax.legend(fontsize=11, loc='upper right')
save(fig, 'gamma_prior')

# Count distribution illustration from eq:dm-mass and eq:multinomial-mass.
fig, ax = plt.subplots(figsize=(8.8, 2.7))
n, total = np.arange(21), 20
ax.plot(n, binom.pmf(n,total,.5), 'o-', color=GREY, ms=4, lw=1.8, label='Multinomial')
ax.plot(n, betabinom.pmf(n,total,2,2), 'o-', color=GREEN, ms=4, lw=2.2,
        label=r'Dirichlet multinomial, $\alpha_0=4$')
ax.set(xlabel='Count for class 1', ylabel='Probability', xticks=[0,5,10,15,20])
ax.legend(fontsize=12)
save(fig, 'count_variance')

# Exact table extracts retain the thesis formatting and precision.
mode_text = analysis_table('mode_sweep')
rows, in_cifar = [], False
for line in mode_text.splitlines():
    if 'textbf{CIFAR-10}' in line: in_cifar = True
    if in_cifar and re.match(r'^\d+ &', line):
        row=cells(line)
        rows.append(' & '.join(row[i] for i in [0,1,3,4])+' \\\\')
tabular('mode_extract.tex', r'\shortstack{Gamma prior\\mode} & \shortstack{realised total\\concentration} & \shortstack{aleatoric\\uncertainty \%} & \shortstack{distributional\\uncertainty \%}', rows, 'cccc')

predictive_text = analysis_table('predictive')
rows=[]
for line in predictive_text.splitlines():
    if 'textbf{Fashion-MNIST}' in line or 'textbf{CIFAR-10}' in line:
        if rows: rows.append(r'\midrule')
        rows.append(line)
    if line.startswith(('Cat-BNN &','Cat-eBNN &')): rows.append(line)
tabular('predictive_extract.tex', 'model & accuracy & NLL', rows, 'lcc')

# Count comparison. Values and seed ranges are parsed from the published table.
prediction_text=analysis_table('count_prediction')
records=[]; initialisation=None
for line in prediction_text.splitlines():
    if 'Cold initialisation' in line: initialisation='Cold'
    if 'Warm initialisation' in line: initialisation='Warm'
    if line.startswith(('M-BNN &','DM-eBNN &')):
        records.append((initialisation,cells(line)))
count_rows=[]
control_rows=[]
for start in ['Cold','Warm']:
    if count_rows: count_rows.append(r'\midrule')
    count_rows.append(r'\multicolumn{4}{l}{\textbf{'+start+r' initialisation}} \\')
    for record_start,row in records:
        if record_start!=start: continue
        count_rows.append(' & '.join(row[i] for i in [0,1,3,4])+r' \\')
        if row[0]=='DM-eBNN':
            control_rows.append(start.lower()+' & '+' & '.join(row[i] for i in [1,2,5])+r' \\')
tabular('count_predictive_extract.tex',r'model & \shortstack{Gamma prior\\mode} & \shortstack{majority label\\accuracy} & count NLL',count_rows,'lccc')
tabular('count_control_extract.tex',r'initialisation & \shortstack{Gamma prior\\mode} & \shortstack{realised total\\concentration} & \shortstack{mean matched\\control NLL}',control_rows,'lccc')

sd_text=analysis_table('sd_sweep')
sd_rows=[]
in_cifar=False
for line in sd_text.splitlines():
    if 'textbf{CIFAR-10}' in line: in_cifar=True
    if in_cifar and re.match(r'^\d+\\% &',line):
        row=cells(line)
        sd_rows.append(' & '.join(row[i] for i in [0,1,4,6])+r' \\')
tabular('sd_extract.tex',r'\shortstack{Gamma prior\\standard deviation} & \shortstack{realised total\\concentration} & \shortstack{distributional\\uncertainty \%} & NLL',sd_rows,'cccc')
fig, ax=plt.subplots(figsize=(10.2,2.75))
groups=[('Cold','50'),('Cold','200'),('Warm','50'),('Warm','200')]
for j,(start,mode) in enumerate(groups):
    baseline=next(r for s,r in records if s==start and r[0]=='M-BNN')
    fitted=next(r for s,r in records if s==start and r[0]=='DM-eBNN' and r[1]==mode)
    for offset,cell,color,label in [(-.20,baseline[4],GREY,'M-BNN'),(0,fitted[4],GREEN,'DM-eBNN'),(.20,fitted[5],ORANGE,'Mean matched control')]:
        mean,low,high=stats(cell)
        ax.errorbar(mean,j+offset,xerr=[[mean-low],[high-mean]],fmt='o',color=color,
                    capsize=3,ms=7,lw=2,label=label if j==0 else None)
ax.set_yticks(range(4),[f'{s.lower()} initialisation\nprior mode {m}' for s,m in groups])
ax.invert_yaxis(); ax.set(xlabel='Count NLL', xlim=(8,38))
ax.legend(loc='upper center',bbox_to_anchor=(.5,1.20),ncol=3,fontsize=11)
ax.grid(axis='x',alpha=.15)
save(fig,'count_prediction')

sensitivity_text=analysis_table('count_prior_sensitivity')
rows=[cells(line) for line in sensitivity_text.splitlines() if line.startswith('warm &')]
fig,ax=plt.subplots(figsize=(9,3.6))
for mode,color in [('50',BLUE),('200',GREEN)]:
    data=[r for r in rows if r[1].startswith(mode+',')]
    values=np.array([stats(r[4]) for r in data])
    ax.errorbar(np.arange(3),values[:,0],yerr=[values[:,0]-values[:,1],values[:,2]-values[:,0]],
                fmt='o-',color=color,lw=2.4,ms=7,capsize=4,label=f'Pretraining prior mode {mode}')
    for pos,value in enumerate(values[:,0]): ax.text(pos,value+6,f'{value:.1f}',ha='center',fontsize=12,color=color)
ax.set_xticks([0,1,2],['20%','100%','No Gamma prior'])
ax.set(xlabel='Gamma prior standard deviation during sampling',ylabel='Realised total concentration',ylim=(35,222))
ax.legend(loc='upper right',fontsize=11)
save(fig,'prior_sensitivity')

uncertainty_text=analysis_table('count_uncertainty')
rows=[cells(line) for line in uncertainty_text.splitlines() if line.startswith(('M-BNN &','DM-eBNN &'))]
fig,ax=plt.subplots(figsize=(10,3.2))
labels=[]
for j,row in enumerate(rows):
    shares=[0 if row[i]=='--' else float(row[i]) for i in [3,4,5]]
    left=0
    for value,color,name in zip(shares,[BLUE,ORANGE,GREEN],['Aleatoric','Distributional','Epistemic']):
        ax.barh(j,value,left=left,color=color,height=.55,label=name if j==1 else None)
        if value:
            ax.text(left+value/2,j,f'{value:.2f}',ha='center',va='center',fontsize=10,
                    color='white' if value>10 else 'black',
                    bbox=None if value>10 else dict(facecolor='white',edgecolor='none',pad=1))
        left+=value
    labels.append(row[0]+('' if row[1]=='--' else f'  prior mode {row[1]}'))
ax.set_yticks(range(3),labels); ax.invert_yaxis()
ax.set(xlabel='Share of predictive uncertainty (%)',xlim=(0,100))
ax.legend(loc='upper center',bbox_to_anchor=(.5,1.23),ncol=3,fontsize=12)
save(fig,'class_decomposition')

# Full tables for backup are copied exactly, never regenerated from numbers.
for name in ['mode_sweep','sd_sweep','predictive','count_prediction','count_prior_sensitivity','count_uncertainty','start_procedure','terms']:
    content=analysis_table(name)
    (tables/f'{name}.tex').write_text(content)

# Thesis diagnostics are copied as final assets, not regenerated.
for name in ['start_trajectory_accuracy','start_trajectory_alpha0','count_collapse_concentration','count_collapse_nll','count_collapse_accuracy','count_collapse_gradient']:
    path=record(args.thesis/'figures'/f'{name}.pdf')
    (figures/f'{name}.pdf').write_bytes(path.read_bytes())

(figures/'sources.json').write_text(json.dumps({
    'generator':'scripts/build_figures.py', 'sources':sources,
    'example_index':example,'example_count_vector':example_counts.tolist(),
    'theory_labels':['eq:dirichlet-density','eq:aleatoric-as-function-of-total-concentration',
                    'eq:gamma-mode','eq:gamma-mean-variance','eq:dm-mass','eq:multinomial-mass'],
},indent=2))
print(f'Generated figures and table extracts. CIFAR-10H image {example}, counts {example_counts.tolist()}.')

# Numerical slide tables preserve the exact reported cells and seed ranges.
def two_lines(cell):
    if r'\,' in cell:
        mean,seed_range=cell.split(r'\,',1)
        return r'\shortstack{'+mean+r'\\'+seed_range+'}'
    return cell

comparison_rows=[]
for start,mode in [('Cold','50'),('Cold','200'),('Warm','50'),('Warm','200')]:
    baseline=next(r for s,r in records if s==start and r[0]=='M-BNN')
    fitted=next(r for s,r in records if s==start and r[0]=='DM-eBNN' and r[1]==mode)
    comparison_rows.append(' & '.join([start.lower(),mode]+[two_lines(c) for c in [baseline[4],fitted[4],fitted[5]]])+r' \\')
tabular('count_comparison_slide.tex',r'initialisation & \shortstack{Gamma prior\\mode} & \shortstack{M-BNN\\count NLL} & \shortstack{DM-eBNN\\count NLL} & \shortstack{mean matched\\control NLL}',comparison_rows,'lcccc')

warm=[cells(line) for line in sensitivity_text.splitlines() if line.startswith('warm &')]
prior_rows=[]
for setting in [r'20\%',r'100\%','none']:
    entries=[]
    for mode in ['50','200']:
        entries.append(next(r[4] for r in warm if r[1].startswith(mode+',') and r[3]==(mode+', '+setting if setting!='none' else 'none')))
    prior_rows.append(' & '.join([setting if setting!='none' else 'no Gamma prior']+entries)+r' \\')
tabular('count_sensitivity_slide.tex',r'\shortstack{Gamma prior\\standard deviation\\during sampling} & \shortstack{pretraining Gamma\\prior mode 50} & \shortstack{pretraining Gamma\\prior mode 200}',prior_rows,'lcc')

share_rows=[]
for line in uncertainty_text.splitlines():
    if line.startswith(('M-BNN &','DM-eBNN &')):
        row=cells(line)
        share_rows.append(' & '.join(row[i] for i in [0,1,3,4,5])+r' \\')
tabular('count_shares_slide.tex',r'model & \shortstack{Gamma prior\\mode} & \shortstack{aleatoric\\uncertainty \%} & \shortstack{distributional\\uncertainty \%} & \shortstack{epistemic\\uncertainty \%}',share_rows,'lcccc')
