"""Extract the M-BNN and mode 200 DM-eBNN decomposition without changing values."""
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = root.parent / 'MSc_thesis/tables/count_uncertainty.tex'
analysis = root.parent / 'BNN-EDL/results/count_uncertainty.tex'
assert source.read_bytes() == analysis.read_bytes()
rows = []
for line in source.read_text().splitlines():
    if not line.startswith(('M-BNN &', 'DM-eBNN &')):
        continue
    cells = [part.strip() for part in line.removesuffix('\\\\').split('&')]
    if cells[0] == 'M-BNN' or cells[1] == '200':
        rows.append(' & '.join(cells[i] for i in [0, 2, 3, 4, 5]) + r' \\')
assert len(rows) == 2
header = (r'Model & \shortstack{Predictive\\uncertainty} & '
          r'\shortstack{Aleatoric\\share (\%)} & '
          r'\shortstack{Distributional\\share (\%)} & '
          r'\shortstack{Epistemic\\share (\%)}')
text = '% Generated by scripts/build_count_decomposition_comparison.py.\n'
text += '% DM-eBNN prior mode 200, prior SD 20 percent. Warm initialisation, three seeds.\n'
text += r'\begin{tabular}{lcccc}' + '\n' + r'\toprule' + '\n'
text += header + r' \\' + '\n' + r'\midrule' + '\n'
text += '\n'.join(rows) + '\n' + r'\bottomrule' + '\n' + r'\end{tabular}' + '\n'
(root / 'tables/count_decomposition_comparison.tex').write_text(text)
