"""Build the introduction prediction chart and editable model diagrams.

The prediction is read from a final evaluation array. The model diagrams are
mathematical illustrations of thesis equations, not experimental findings.
Only the presentation directory receives output files.
"""
from pathlib import Path
import argparse,hashlib,json
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

root=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser()
parser.add_argument('--experiments',type=Path,default=root.parent/'BNN-EDL')
parser.add_argument('--thesis',type=Path,default=root.parent/'MSc_thesis')
args=parser.parse_args()
figures=root/'figures';tables=root/'tables'
sources={}
def record(p):
    source_name=str(p.relative_to(root)) if p.is_relative_to(root) else str(p)
    sources[source_name]=hashlib.sha256(p.read_bytes()).hexdigest()
    return p

# Same final BMA as analysis/common/predictive.py, without importing into the source repo.
record(args.experiments/'analysis/common/predictive.py')
path=record(args.experiments/'outputs/e1_c10_bnn_T1_warm_s0/arrays/cifar10_test.npz')
a=np.load(path,allow_pickle=False)
index=4195
pos=int(np.flatnonzero(a['index']==index)[0])
prob=np.asarray(a['snapshot_means'],dtype=np.float64).mean(axis=0)[pos]
classes=['airplane','automobile','bird','cat','deer','dog','frog','horse','ship','truck']
predicted=int(np.argmax(prob))
assert predicted==int(a['pred_class'][pos])
record(figures/'cifar10h_example.png')
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':13,'axes.labelsize':14,
 'axes.spines.top':False,'axes.spines.right':False,'axes.spines.left':False,
 'pdf.fonttype':42,'savefig.facecolor':'white'})
fig,ax=plt.subplots(figsize=(5.9,3.45))
ax.barh(np.arange(10),prob,color=['#00883a' if c==predicted else '#326a9f' for c in range(10)],height=.64)
ax.set_yticks(np.arange(10),classes);ax.invert_yaxis()
ax.tick_params(axis='y',length=0,pad=7)
ax.set(xlim=(0,1),xticks=[0,.5,1],xlabel='Predicted class probability')
ax.tick_params(axis='x',colors='black');ax.spines['bottom'].set_color('black')
fig.savefig(figures/'intro_prediction.pdf',bbox_inches='tight',pad_inches=.1)
plt.close(fig)
(tables/'intro_prediction.tex').write_text('\\newcommand{\\introclass}{'+classes[predicted]+'}\n')

# Native LaTeX diagrams. Bar lengths follow the Dirichlet mean and categorical
# likelihood in thesis eq:general-dirichlet-mean and eq:categorical-likelihood.
record(args.thesis/'chapters/background.tex')
record(args.thesis/'chapters/discussion.tex')
concentrations=np.array([[8.,2.],[6.,4.],[3.,7.]])
means=concentrations/concentrations.sum(axis=1,keepdims=True)
rng=np.random.default_rng(14)
possible_vectors=rng.dirichlet(concentrations[1],size=3)

def text_at(x,y,text,w=0,align='l',size=r'\small'):
    return rf'\put({x},{y}){{\makebox({w},4)[{align}]{{{size} {text}}}}}'
def arrow(x,y,length,direction=(1,0)):
    return rf'\put({x},{y}){{\vector({direction[0]},{direction[1]}){{{length}}}}}'
def bar(x,y,p,width=17):
    return (rf'\put({x},{y}){{\hbox{{\color{{lmugreen}}\rule{{{width*p:.6f}mm}}{{3mm}}'
            rf'\color{{introblue}}\rule{{{width*(1-p):.6f}mm}}{{3mm}}}}}}')

lines=[r'% Generated by scripts/build_intro_figures.py.',
 r'% Source. Background 2.7, eq:three-way-decomposition. Two class model illustration.',
 r'\setlength{\unitlength}{1mm}',r'\begin{picture}(140,51)']
# A single diagram builds over three overlays. Future rows are hidden, never grey.
lines += [r'\only<1->{',text_at(0,44,r'\textbf{Epistemic uncertainty}'),
 text_at(0,38,'Plausible network weights')]
for j,(x,m) in enumerate(zip([54,89,124],means)):
    lines += [text_at(x,47,rf'$w^{{({j+1})}}$',align='c'),arrow(x,46,3,(0,-1)),bar(x-8.5,38,m[0])]
lines += [r'}',r'\only<2->{',text_at(0,26,r'\textbf{Distributional uncertainty}'),
 text_at(0,20,'Fixed network weights'),text_at(51,22,r'$w$',align='c'),arrow(60,24,6)]
for x,vec in zip([77,101,125],possible_vectors):lines += [bar(x-8.5,22,vec[0])]
lines += [r'}',r'\only<3->{',text_at(0,8,r'\textbf{Aleatoric uncertainty}'),
 text_at(0,1,r'\shortstack[l]{Fixed class-probability\\vector}'),bar(46,5,means[1,0]),arrow(67,6.5,12),
 text_at(85,4,r'\textcolor{lmugreen}{Class A}\quad or\quad\textcolor{introblue}{Class B}'),r'}',r'\end{picture}']
(figures/'intro_terms.tex').write_text('\n'.join(lines)+'\n')

lines=[r'% Generated by scripts/build_intro_figures.py.',
 r'% Source. Discussion 6.1. Background eq:point-mass-definition, eq:degenerate-distributional-term, eq:fixed-weight-dirichlet.',
 r'\setlength{\unitlength}{1mm}',r'\begin{picture}(140,53)']
for offset,name,left,middle,lterm,mterm in [
 (28,r'\textbf{Categorical Bayesian neural network (Cat-BNN)}',r'Weight posterior',r'\shortstack{One class-probability vector\\at each weight configuration}',r'Epistemic uncertainty',r'\textbf{Distributional term zero}'),
 (0,r'\textbf{Evidential deep learning (EDL)}',r'One weight estimate',r'\shortstack{Dirichlet distribution over\\class-probability vectors}',r'\textbf{Epistemic term zero}',r'Distributional uncertainty')]:
    lines += [text_at(0,offset+20,name,size=r'\normalsize'),
      text_at(22,offset+10,left,align='c'),arrow(44,offset+12,6),
      text_at(79,offset+10,middle,align='c'),arrow(109,offset+12,6),
      text_at(128,offset+10,'Class label',align='c'),
      text_at(22,offset+1,lterm,align='c'),
      text_at(79,offset+1,mterm,align='c'),
      text_at(128,offset+1,'Aleatoric uncertainty',align='c')]
lines += [r'\end{picture}']
(figures/'intro_complementary.tex').write_text('\n'.join(lines)+'\n')
(figures/'intro_sources.json').write_text(json.dumps({
 'generator':'scripts/build_intro_figures.py','sources':sources,
 'prediction':{'run':path.parent.parent.name,'image_index':index,'row':pos,
 'weight_samples':int(a['snapshot_means'].shape[0]),'probabilities':prob.tolist(),
 'predicted_class':classes[predicted]},
 'model_illustration':{'concentrations':concentrations.tolist(),
 'possible_class_probability_vectors':possible_vectors.tolist(),'random_seed':14,
 'theory_labels':['eq:three-way-decomposition','eq:general-dirichlet-mean','eq:categorical-likelihood']}
},indent=2))
print('Built introduction prediction and editable diagrams from recorded sources.')
