"""Extract both datasets and all modes from the unchanged thesis mode sweep."""
from pathlib import Path
import hashlib
import json
import re

root=Path(__file__).resolve().parents[1]
source=root.parent/'MSc_thesis'/'tables'/'mode_sweep.tex'
text=source.read_text()
groups={'Fashion-MNIST':[],'CIFAR-10':[]}
current=None
for line in text.splitlines():
    for dataset in groups:
        if r'\textbf{'+dataset+'}' in line:
            current=dataset
    if current and re.match(r'^\d+ &',line):
        cells=[cell.strip() for cell in line.removesuffix(r'\\').split('&')]
        assert len(cells)==7
        groups[current].append(' & '.join([cells[i] for i in (0,2,3,4,5)])+r' \\')
assert [len(rows) for rows in groups.values()]==[4,3]
header=r'''% Generated by scripts/build_cat_mode_decomposition.py from the unchanged thesis table.
\begin{tabular}{ccccc}
\toprule
\shortstack{Prior\\mode} & \shortstack{Predictive\\entropy} & \shortstack{Aleatoric\\\%} & \shortstack{Distributional\\\%} & \shortstack{Epistemic\\\%} \\
\midrule
'''
sections=[]
for dataset,rows in groups.items():
    sections.append(r'\multicolumn{5}{l}{\textbf{'+dataset+r'}} \\'+'\n'+'\n'.join(rows))
(root/'tables/cat_mode_decomposition.tex').write_text(header+'\n\\midrule\n'.join(sections)+'\n\\bottomrule\n\\end{tabular}\n')
(root/'tables/cat_mode_decomposition.sources.json').write_text(json.dumps({
    'generator':'scripts/build_cat_mode_decomposition.py','source':str(source),
    'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
    'thesis_label':'tab:e2-mode-sweep',
    'selection':'Fashion-MNIST and CIFAR-10, all seven reported rows, prior mode, predictive entropy and three uncertainty shares',
    'formatting':'Every selected numerical cell is preserved, including the reported seed range.'
},indent=2)+'\n')
print('Extracted both datasets and all seven modes with unchanged numeric cells.')
