"""Extract cold and warm Gamma sensitivity results without changing reported cells."""
from pathlib import Path


def build_table(thesis, experiments, output):
    source = Path(thesis) / 'tables/count_prior_sensitivity.tex'
    analysis = Path(experiments) / 'results/count_prior_sensitivity.tex'
    assert source.read_bytes() == analysis.read_bytes()
    rows = [
        [c.strip() for c in line.removesuffix('\\\\').split('&')]
        for line in source.read_text().splitlines() if line.startswith(('cold &', 'warm &'))
    ]
    assert len(rows) == 7
    body = []
    previous_mode = None
    for row in rows:
        if row[0] == 'cold':
            mode = r'\shortstack{None\\(cold)}'
        else:
            mode, pretrain_sd = row[1].split(', ')
            assert pretrain_sd == r'20\%'
        if previous_mode is not None and previous_mode != mode:
            body.append(r'\midrule')
        setting = 'No Gamma prior' if row[3] == 'none' else row[3].split(', ')[1]
        body.append(' & '.join([mode, setting, row[4], row[5], row[6]]) + r' \\')
        previous_mode = mode
    header = (
        r'\shortstack{Pretraining\\prior mode} & '
        r'\shortstack{SGLD prior SD\\(\% of mode)} & '
        r'\shortstack{Realised total\\concentration} & '
        r'\shortstack{Majority label\\accuracy} & '
        r'\shortstack{Count NLL\\$\downarrow$ better}'
    )
    text = '% Generated by scripts/build_count_sensitivity_table.py from unchanged thesis and analysis tables.\n'
    text += r'\begin{tabular}{ccccc}' + '\n' + r'\toprule' + '\n'
    text += header + r' \\' + '\n' + r'\midrule' + '\n'
    text += '\n'.join(body) + '\n' + r'\bottomrule' + '\n' + r'\end{tabular}' + '\n'
    Path(output).write_text(text)


if __name__ == '__main__':
    root = Path(__file__).resolve().parents[1]
    build_table(root.parent / 'MSc_thesis', root.parent / 'BNN-EDL',
                root / 'tables/count_sensitivity_slide.tex')
