"""Extract warm count predictions at prior mode 200, preserving thesis cells."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = root.parent / "MSc_thesis/tables/count_prediction.tex"
rows = []
control_rows = []
warm = False
for line in source.read_text().splitlines():
    if "Warm initialisation" in line:
        warm = True
    if warm and line.startswith(("M-BNN &", "DM-eBNN &")):
        cells = [cell.strip() for cell in line.removesuffix(r"\\").split("&")]
        if cells[0] == "DM-eBNN" and cells[1] != "200":
            continue
        rows.append(" & ".join(cells[i] for i in (0, 3, 4)) + r" \\")
        if cells[0] == "DM-eBNN":
            control_rows.append(" & ".join(cells[i] for i in (4, 5)) + r" \\")
assert len(control_rows) == 1
assert len(rows) == 2
header = r"""% Generated by scripts/build_count_predictive_warm.py from unchanged thesis cells.
\begin{tabular}{lcc}
\toprule
model & \shortstack{majority label\\accuracy} & count NLL \\
\midrule
\multicolumn{3}{l}{\textbf{CIFAR-10H}} \\
"""
(root / "tables/count_predictive_warm.tex").write_text(header + "\n".join(rows) + "\n" + r"\bottomrule" + "\n" + r"\end{tabular}" + "\n")

control_header = r"""% Generated by scripts/build_count_predictive_warm.py from unchanged thesis cells.
\begin{tabular}{cc}
\toprule
\shortstack{DM-eBNN\\count NLL} & \shortstack{Mean matched control\\count NLL} \\
\midrule
\multicolumn{2}{l}{\textbf{CIFAR-10H}} \\
"""
(root / "tables/count_mean_matched_warm.tex").write_text(control_header + "\n".join(control_rows) + "\n" + r"\bottomrule" + "\n" + r"\end{tabular}" + "\n")
